import { TableCell, TableHead, TableRow } from "@material-ui/core";
import React, { useEffect, useState } from "react";
// import { useSortableData } from "./table.sort";

const outwardsHeadCells = [
  { id: "order", label: "Order No." },
  { id: "shipping", label: "Shipping Date" },
  { id: "item", label: "Item Name" },
  { id: "agency", label: "Agency Name" },
  { id: "quantity", label: "Total Qty." },
  { id: "dc_numver", label: "DC Number" },
  { id: "generated_by", label: "Generated by" },
  { id: "status", label: "Status" },
  { id: "delivery_date", label: "Delivery Date" },
  { id: "more", label: "More" },
];

const inwardsHeadCells = [
  { id: "order", label: "Order No." },
  { id: "agency", label: "Agency Name" },
  { id: "item", label: "Item Name" },
  { id: "goodCondition", label: "Good Condition" },
  { id: "notWorking", label: "Not Working" },
  { id: "damaged", label: "Damaged" },
  { id: "receivingDate", label: "Receiving Date" },
  { id: "audit", label: "Audit" },
  { id: "more", label: "More" },
];
const clientsHeadCells = [
  { id: "agency", label: "Agency Name" },
  { id: "client_id", label: "Client ID" },
  { id: "date", label: "Date" },
  { id: "name", label: "Name" },
  { id: "email", label: "Email" },
  { id: "location", label: "Location/City" },
  { id: "orders", label: "Orders" },
];

const inventoryHeadCells = [
  { id: "img", label: "Image" },
  { id: "item_name", label: "Item Name" },
  { id: "code", label: "Code" },
  { id: "purchase_count", label: "Purchase Count" },
  { id: "onHand", label: "On Hand" },
  { id: "client_count", label: "Client Count" },
  { id: "not_working", label: "Not Working" },
  { id: "damaged", label: "Damaged" },
  { id: "missing", label: "Missing" },
  { id: "more", label: "More" },
];

const purchaseHistoryHeadCells = [
  { id: "item_name", label: "Item Name" },
  { id: "order_no", label: "Order No." },
  { id: "supplier_name", label: "Supplier Name" },
  { id: "purchase_count", label: "Purchase Count" },
  { id: "purchase_date", label: "Purchase Date" },
  { id: "more", label: "More" },
];

const employeesHeadCells = [
  { id: "id", label: "ID No." },
  { id: "item_name", label: "Employee Name" },
  { id: "role", label: "Role" },
  { id: "phone_number", label: "Phone Number" },
  { id: "status", label: "Status" },
  { id: "more", label: "More" },
];

const TableHeadCell = (props) => {
  const [data, setData] = useState([]);
  const {
    classes,
    order,
    orderBy,
    // onRequestSort,
    show,
    requestSort,
    getClassNamesFor,
  } = props;
  // const createSortHandler = (property) => (event) => {
  //   onRequestSort(event, property);
  // };
  useEffect(() => {
    if (show === "inwardsTable") {
      return setData(inwardsHeadCells);
    }
    if (show === "outwardsTable") {
      return setData(outwardsHeadCells);
    }
    if (show === "clientsTable") {
      return setData(clientsHeadCells);
    }
    if (show === "inventory") {
      return setData(inventoryHeadCells);
    }
    if (show === "purchaseHistory") {
      return setData(purchaseHistoryHeadCells);
    }
    if (show === "employees") {
      return setData(employeesHeadCells);
    }
  }, []);

  return (
    <TableHead>
      <TableRow>
        {data.map((headCell) => (
          <TableCell
            align={headCell.align ? headCell.align : "center"}
            key={headCell.id}
            sortDirection={orderBy === headCell.id ? order : false}
            active={orderBy === headCell.id}
            direction={orderBy === headCell.id ? order : "asc"}
            onClick={() => requestSort(headCell.id)}
            className={(getClassNamesFor(headCell.id), classes.thead)}
          >
            {headCell.label}
          </TableCell>
        ))}
      </TableRow>
    </TableHead>
  );
};

export default TableHeadCell;
