export const inventoryHeadCells = [
  { id: "sortOff", label: "Image" },
  { id: "item_name", label: "Item Name" },
  { id: "code", label: "Code" },
  { id: "quantity", label: "Purchase Count" },
  { id: "onHand", label: "On Hand" },
  { id: "clientCount", label: "Client Count" },
  { id: "not_working", label: "Not Working" },
  { id: "damaged", label: "Damaged" },
  { id: "yetRecieve", label: "Yet to recieve" },
  { id: "sortOff", label: "More" },
];

export const purchaseHistoryHeadCells = [
  { id: "sortOff", label: "Item Name" },
  { id: "order_no", label: "Order No." },
  { id: "supplier", label: "Supplier Name" },
  { id: "sortOff", label: "Purchase Count" },
  { id: "purchase_date", label: "Purchase Date" },
  { id: "sortOff", label: "More" },
];

export const outwardsHeadCells = [
  { id: "key", label: "Order No." },
  { id: "shippingDate", label: "Shipping Date" },
  { id: "sortOff", label: "Item Name" },
  { id: "agency", label: "Agency Name" },
  { id: "sortOff", label: "Sent Qty." },
  // { id: "pincode", label: "Pincode" },
  // { id: "generated_by", label: "Generated by" },
  { id: "status", label: "Status" },
  { id: "deliveryDate", label: "Delivery Date" },
  { id: "sortOff", label: "More" },
];

export const inwardsHeadCells = [
  { id: "key", label: "Order No." },
  { id: "agency", label: "Agency Name" },
  { id: "sortOff", label: "Item Name" },
  { id: "sortOff", label: "Received" },
  { id: "sortOff", label: "Good Condition" },
  // { id: "sortOff", label: "Not Working" },
  { id: "sortOff", label: "Damaged" },
  { id: "receivedDate", label: "Receiving Date" },
  { id: "auditStatus", label: "Audit" },
  { id: "sortOff", label: "More" },
];

export const employeesHeadCells = [
  { id: "id", label: "ID No." },
  { id: "displayName", label: "Employee Name" },
  { id: "role", label: "Role" },
  { id: "phoneNumber", label: "Phone Number" },
  { id: "status", label: "Status" },
  { id: "sortOff", label: "More" },
];

export const clientsHeadCells = [
  { id: "name", label: "Agency Name" },
  { id: "id", label: "Client ID" },
  // { id: "date", label: "Date" },
  { id: "supervisor", label: "Name" },
  { id: "email", label: "Email" },
  { id: "city", label: "Location/City" },
  { id: "orders", label: "Orders" },
];
