import React, { useEffect, useRef } from "react";
import { Col, Row } from "react-bootstrap";
import styled from "styled-components";
import dateFormat from "dateformat";
import {
  AddItemContainer,
  ApplyFormInput,
  Button,
  DemoItemInput,
  InputDiv,
  Label,
  MainTitle,
  TableInput,
  TableSelect,
  TextAreaInput,
} from "../../../styles/styles";
import {
  makeStyles,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
} from "@material-ui/core";
import { scrollToRef } from "../../../ScrollTop";
import TopbarAtom from "../../../atoms/TopbarAtom";
import DocumentPreview from "../../../atoms/DocumentPreview";

const useStyles = makeStyles({
  table: {
    width: "80%",
    paddingTop: "30px",
    margin: "0 auto",
  },
  thead: {
    borderBottom: "none",
    fontFamily: "Poppins",
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "21px",
    color: "#6D83AE",
    background: "#F7F9FD",
  },
  button: {
    display: "block",
    marginTop: "20px",
  },
  formControl: {
    margin: "10px",
    minWidth: 120,
  },
});

const ViewMoreOutwards = ({ setShow, details, setDetails }) => {
  // console.log("🚀 ~ ViewMoreOutwards ~ details", details)
  const classes = useStyles();
  const topbarRef = useRef(null);
  useEffect(() => {
    scrollToRef(topbarRef);
  }, []);

  return (
    <div>
      <TopbarAtom
        topRef={topbarRef}
        title="Outward Details"
        goBack="outwardsTable"
      />
      <AddItemContainer>
        <form>
          <Container>
            <MainTitle style={{ paddingTop: "10px" }}>Agency Details</MainTitle>
            <Row className="w-100 p-0 m-0">
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Agency Name</Label>
                  <ApplyFormInput details readOnly value={details.agency} />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Receiver's Name</Label>
                  <ApplyFormInput details readOnly value={details.receiver} />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Phone Number</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.phone_number}
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Email</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.email}
                    type="email"
                  />
                </InputDiv>
              </Col>
            </Row>

            <MainTitle>Order Details</MainTitle>
            <Row className="w-100 p-0 m-0">
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Order Generated by</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.generated_by}
                    type="text"
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Reference Number</Label>
                  <ApplyFormInput details readOnly value={details.reference} />
                </InputDiv>
              </Col>
              {/* <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>P.O Number</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.phone_number}
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>P.I Number</Label>
                  <ApplyFormInput details readOnly value={details.piNumber ? details.piNumber : "-"} />
                </InputDiv>
              </Col> */}
              <DocumentPreview label="Eway Bill" docFile={details.ewayBill} />
              <DocumentPreview
                label="D.C Document"
                docFile={details.dcDocument}
              />
              <DocumentPreview
                label="Courier Document"
                docFile={details.courierDoc}
              />
              <DocumentPreview
                label="Packaging List"
                docFile={details.packagingList}
              />
              {/* <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Eway Bill</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.ewayBill}
                    type="text"
                  />
                </InputDiv>
              </Col> */}
              {/* <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>D.C Number</Label>
                  <ApplyFormInput details readOnly value={details.dcNumber} />
                </InputDiv>
              </Col> */}
            </Row>
            <MainTitle>Delivery Details</MainTitle>
            <Row className="w-100 p-0 m-0">
              <Col md={6} xs={12}>
                <InputDiv>
                  <Label details>Address</Label>
                  <TextAreaInput
                    details
                    readOnly
                    value={details.address}
                    type="text"
                    rows="5"
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>City</Label>
                  <ApplyFormInput details readOnly value={details.city} />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>District</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.district}
                    type="text"
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>State</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.state}
                    type="text"
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Pincode</Label>
                  <ApplyFormInput details readOnly value={details.pincode} />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Mode of Transportation</Label>

                  <ApplyFormInput
                    details
                    readOnly
                    value={details.transport ? details.transport : "N/A"}
                    type="text"
                  />
                </InputDiv>
              </Col>
              <Col md={3} xs={12}>
                <InputDiv>
                  <Label details>Delivery Date</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={
                      details.deliveryDate &&
                      dateFormat(new Date(details?.deliveryDate), "dd-mm-yyyy")
                    }
                  />
                </InputDiv>
              </Col>
              <Col md={12} xs={12}>
                <InputDiv>
                  <Label details>Remarks</Label>
                  <ApplyFormInput
                    details
                    readOnly
                    value={details.remarks}
                    type="text"
                  />
                </InputDiv>
              </Col>
            </Row>
          </Container>
          <AddItemsContainer>
            <Container>
              <MainTitle>Add Items</MainTitle>
              <Table className={classes.table} aria-label="simple table">
                <TableHead>
                  <TableRow>
                    <TableCell className={classes.thead} align="center">
                      #
                    </TableCell>
                    <TableCell className={classes.thead} align="center">
                      Item Code
                    </TableCell>
                    <TableCell className={classes.thead} align="center">
                      Item
                    </TableCell>
                    <TableCell className={classes.thead} align="center">
                      Sent Qty.
                    </TableCell>
                    <TableCell
                      className={classes.thead}
                      align="center"
                    ></TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {details?.item?.map((item, index) => {
                    return (
                      <TableRow key={item.id}>
                        <TableCell align="center">{index + 1}</TableCell>
                        <TableCell align="center">
                          <TableInput
                            style={{ border: "none" }}
                            readOnly
                            value={`${item.code}`}
                          />
                        </TableCell>
                        <TableCell align="center">
                          <DemoItemInput readOnly value={`${item.name}`} />

                          {/* <TableSelect
                            name={`item[${index}].name`}
                            readOnly
                            value={`${item.item}`}
                          >
                            <option readOnly value={item.name}>
                              {item.name}
                            </option>
                          </TableSelect> */}
                        </TableCell>
                        <TableCell align="center">
                          <TableInput
                            type="number"
                            name={`item[${index}].quantity`}
                            readOnly
                            value={`${item.sent}`}
                          ></TableInput>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </Container>
          </AddItemsContainer>
          <div className="text-center mt-lg-5 my-2">
            <Button
              outline
              onClick={() => {
                setShow("outwardsTable");
                setDetails({});
              }}
            >
              Go back
            </Button>
          </div>
        </form>
      </AddItemContainer>
    </div>
  );
};

export default ViewMoreOutwards;

const AddItemsContainer = styled.div`
  @media only screen and (max-width: 1000px) {
    overflow-x: scroll;
  }
`;
const Container = styled.div`
  padding: 0 50px;
  @media only screen and (max-width: 1000px) {
    padding: 0;
  }
`;
